server:
  tomcat:
    uri-encoding: UTF-8
  max-http-request-header-size: 80KB

spring:
  application:
    name: template
  servlet:
    multipart:
      max-file-size: 10MB     # 文件上传大小限制为500kb
      max-request-size: 10MB  # 请求大小限制为500kb
  rabbitmq: # RabbitMQ配置
    host: 10.66.231.33
    port: 5672
    username: admin
    password: admin@123
    virtual-host: /

itiaoling:
  mq:
    exchange-name: alarm-probe-exchange
    bindings:
      - binding-queue-name: metric-queue
        routing-key: metric-queue-key



